# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Place.create([ [name: "Sala 1"], [name: "Sala 2"], [name: "Sala 3"], [name: "Sala 4"], [name: "Sala 5"] ])

Role.create([ [name: 'exacto'], [name: 'popular'], [name: 'diverso'] ])

Item.create([ 
    [hierarchy_id: 9, place_id: 1, description: 'El león (Panthera leo) es un mamífero carnívoro de la familia de los félidos y una de las 4 especies del género Panthera. Algunos machos, excepcionalmente grandes, llegan a pesar hasta 250 kg, lo que los convierte en el segundo félido viviente más grande después del tigre. Los leones salvajes viven en África subsahariana y Asia, con una población en peligro crítico al noroeste de la India, habiendo desaparecido del norte de África, de Oriente Próximo y del oeste de Asia en tiempos históricos.', visits: 0, name: 'León', cientific_name: 'Panthera Leo', visible: 1],
    [hierarchy_id: 9, place_id: 1, description: 'El tigre (Panthera tigris) es una de las seis especies de la subfamilia de los panterinos (familia Felidae) pertenecientes al género Panthera. Se encuentra solamente en el continente asiático; es un predador carnívoro y es la especie de felino más grande del mundo, pudiendo alcanzar un tamaño comparable al de los felinos fósiles de mayor tamaño.', visits: 0, name: 'Tigre', cientific_name: 'Panthera Tigris', visible: 1],
    [hierarchy_id: 7, place_id: 2, description: 'El lobo (Canis lupus) es una especie de mamífero placentario del orden de los carnívoros. El perro doméstico (Canis lupus familiaris) se considera miembro de la misma especie según distintos indicios, la secuencia del ADN y otros estudios genéticos.2 Los lobos fueron antaño abundantes y se distribuían por Norteamérica, Eurasia y el Oriente Medio. Actualmente, por una serie de razones relacionadas con el hombre, incluyendo el muy extendido hábito de la caza, los lobos habitan únicamente en una muy limitada porción del que antes fue su territorio.', visits: 1, name: 'Lobo', cientific_name: 'Canis Lupus', visible: 1],
    [hierarchy_id: 7, place_id: 3, description: 'El lobo rojo (Canis rufus) es un cánido de taxonomía históricamente dudosa que hoy sólo se puede encontrar en algunas zonas del este de Estados Unidos, México y, tal vez, sureste de Canadá. Se le clasifica ahora como una subespecie de lobo (Canis lupus), aunque, tal vez, sea una población híbrida reciente entre lobo y coyote (Canis latrans), o, cómo anteriormente se le consideraba, una especie independiente de ambas, Canis rufus. En cualquier caso, el lobo rojo es un animal en grave peligro de extinción, razón por la cual es objeto de programas de cría en cautividad.', visits: 0, name: 'Lobo Rojo', cientific_name: 'Canis Rufus', visible: 1],
    [hierarchy_id: 3, place_id:4, description: 'La cabra o chiva (Capra aegagrus hircus) es un mamífero artiodáctilo de la subfamilia Caprinae que fue domesticado alrededor del VIII milenio a. C., sobre todo por su carne y leche. Al macho de la cabra se le llama cabrón, cabro, chivato, macho cabrío o irasco, y a las crías, cabrito o chivo. Al conjunto de estos animales, criados por el ser humano, se le conoce como ganado caprino o ganado cabrío.', visits: 0, name: 'Cabra', cientific_name: 'Capra aegagrus hircus', visible: 1],
    [hierarchy_id: 3, place_id:4, description: 'El panda o panda gigante (Ailuropoda melanoleuca) es una especie de mamífero del orden de los carnívoros y, aunque hay una gran controversia al respecto, los últimos estudios de su ADN lo engloban entre los miembros de la familia de los osos (Ursidae), siendo el oso de anteojos su pariente más cercano, si bien este pertenece a la subfamilia de los tremarctinos. Por otro lado, el panda rojo pertenece a una familia propia e independiente; Ailuridae. Nativo de China central, el panda gigante habita en regiones montañosas como Sichuan y el Tíbet, hasta una altura de 3500 msnm.', visits: 0, name: 'Panda Gigante', cientific_name: 'Ailuropoda melanoleuca', visible: 1],
    [hierarchy_id: 1, place_id:4, description: 'El cocodrilo de las marismas (Crocodylus palustris), también llamado cocodrilo iraní, hocicudo, hindú o persa, es una especie de cocodrílidos que se localiza por todo el subcontinente indio y las fronteras de los países vecinos (Pakistán, Sri Lanka, etc.). En las regiones costeras de Pakistán, por el Makrán y las marismas del delta del Sindh se le conoce como cocodrilo hindú, ya que existe en varias zonas de Bangladés, y partes de Nepal e Irán. En inglés recibe el nombre de Mugger Crocodile. La palabra "mugger" es una transformación de la palabra Hindi/Urdu "magar", que significa monstruo acuático.1 2 Y ésta, a su vez, deriva de "makara", la palabra usada para referirse a un cocodrilo en sánscrito.', visits: 0, name: 'Cocodrilo Iraní', cientific_name: 'Crocodylus palustris', visible: 1],
    [hierarchy_id: 1, place_id:4, description: 'El rinoceronte blanco (Ceratotherium simum) es una especie de mamífero perisodáctilo de la familia Rhinocerotidae.2 Es la mayor de las cinco especies de rinocerontes que existen en la actualidad, el cuarto animal terrestre más grande y el cuarto mamífero terrestre más pesado después de las tres especies de elefantes. Puede llegar a los 4,2 metros de longitud y 1,85 metros de altura. Es una de las dos especies de rinocerontes que viven en la sabana africana, la otra es el rinoceronte negro (Diceros bicornis). Ambas tienen dos cuernos y están medianamente amenazadas por culpa de la caza furtiva.', visits: 0, name: 'Rinoceronte Blanco', cientific_name: 'Ceratotherium simum', visible: 1],
    [hierarchy_id: 1, place_id:4, description: 'El berrendo o antílope americano (Antilocapra americana) es una especie de mamífero artiodáctilo de la familia Antilocapridae. Se trata del único representante actual de su familia, aunque hasta principios del Pleistoceno contaba con numerosas especies. Con el paso del tiempo, todos se extinguieron por diversas causas, dejando al berrendo actual como único vestigio de su presencia.', visits: 0, name: 'Antílope Americano', cientific_name: 'Antilocapra americana', visible: 1],
    [hierarchy_id: 1, place_id:4, description: 'Los camaleones (Chamaeleonidae, del griego chamai, ‘en la tierra’, ‘en el suelo’ y del latín, leo, ‘león’; ‘león de tierra’) son una familia de pequeños saurópsidos (reptiles) escamosos. Existen cerca de 161 especies de camaleones, la mayor parte de ellas en África al sur del Sáhara. En América se llama a menudo camaleones a lagartos de la familia de los anoles, que no guardan ningún parentesco especial con los verdaderos camaleones. Son famosos por su habilidad de cambiar de color según las circunstancias, por su lengua rápida y alargada, y por sus ojos, que pueden ser movidos independientemente el uno del otro. El grupo es bastante antiguo, ya que se conocen fósiles de camaleón procedentes del Paleoceno. La familia está emparentada con la de los agámidos.', visits: 0, name: 'Camaleón', cientific_name: 'Chamaeleonidae', visible: 1]
  ])

User.create([ [name: "adulto", role_id: 3], [name: "child", role_id: 2], [name: "guia", role_id: 1] ])

DataStream.create([
    [item_id: 1, role_id: 2, url: 'https://www.youtube.com/watch?v=ANbukSJdu3k', data_type: 'Video'],
    [item_id: 2, role_id: 2, url: 'https://www.youtube.com/watch?v=lolT5nIQIY4', data_type: 'Video'],
    [item_id: 3, role_id: 1, url: 'https://www.youtube.com/watch?v=PnAUMomuY9o', data_type: 'Video'],
    [item_id: 4, role_id: 3, url: 'http://www.youtube.com/watch?v=l2Bvbd9xo4g', data_type: 'Video'],
    [item_id: 5, role_id: 3, url: 'http://www.youtube.com/watch?v=-VsfJadK_sg', data_type: 'Video'],
    [item_id: 6, role_id: 3, url: 'http://animaldiversity.ummz.umich.edu/collections/contributors/david_blank/pandaeating/medium.jpg', data_type: 'Imagen'],
    [item_id: 7, role_id: 3, url: 'http://www.youtube.com/watch?v=vWPl50YpjLA', data_type: 'Video'],
    [item_id: 8, role_id: 3, url: 'http://www.youtube.com/watch?v=Drc7k5IQfXY', data_type: 'Video'],
    [item_id: 9, role_id: 3, url: 'http://www.youtube.com/watch?v=FLxYl9HAx-Y', data_type: 'Video'],
    [item_id: 10, role_id: 3, url: 'http://www.youtube.com/watch?v=oZ8nemk_RFg', data_type: 'Video']
  ])

Hierarchy.create([ 
    [name: 'Chordata', description: 'Los cordados (Chordata) son un filo del reino animal caracterizado por cinco sinapomorfias, la más destacada de las cuales es la presencia de una cuerda dorsal o notocorda (o notocordio) de células turgentes por lo menos en alguna fase del desarrollo.', parent_id: 9],
    [name: 'Vertebrata', description: 'Los vertebrados (Vertebrata) son un subfilo muy diverso de cordados que comprende a los animales con espina dorsal o columna vertebral, compuesta de vértebras.', parent_id: 2],
    [name: 'Mammalia', description: 'Los mamíferos (Mammalia) son una clase de vertebrados amniotas homeotermos (de \"sangre caliente\"), con pelo y glándulas mamarias productoras de leche con la que alimentan a las crías.',parent_id: 3],
    [name: 'Carnivora', description: 'Los carnivora hace alusión a los mamíferos que, en ese sistema de clasificación, se consideran miembros de esa categoría por entenderse que pertenecen a una línea evolutiva de animales adaptados a la ingestión principalmente de carne, tanto si la especie concreta tiene la carne como su alimento principal como si no es así.', parent_id: 4],
    [name: 'Felidae', description: 'Los félidos (Felidae) son una familia de mamíferos placentarios del orden Carnivora. Poseen un cuerpo esbelto, oído agudo y excelente vista. Son los mamíferos cazadores más sigilosos.', parent_id: 5],
    [name: 'Canidae', description: 'Los cánidos (Canidae) son una familia de mamíferos del orden Carnivora, de régimen carnívoro u omnívoro. Abarca a lobos (incluyendo perros), dingos, zorros, coyotes y chacales. Estos animales son digitígrados. Sus principales características incluyen hocico largo y cuerpo comprimido.', parent_id: 5],
    [name: 'Canis', description: 'Canis es un género de mamíferos placentarios de la familia Canidae, orden de los carnívoros, que incluye los perros, lobos, dingos, chacales y coyotes.', parent_id: 7],
    [name: 'Animalia', description: 'En la clasificación científica de los seres vivos, el reino Animalia (animales) o Metazoa (metazoos) constituye un amplio grupo de organismos eucariotas, heterótrofos, pluricelulares y tisulares. Se caracterizan por su capacidad para la locomoción, por la ausencia de clorofila y de pared en sus células, y por su desarrollo embrionario.',parent_id: nil],
    [name: 'Panthera', description: 'Panthera es un género de mamíferos de la familia Felidae, al que pertenecen cinco especies muy conocidas: el tigre, el león, el leopardo, el jaguar y el leopardo de las nieves. El género comprende aproximadamente la mitad de los grandes félidos.',parent_id: 6] 
  ])
